import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome';
import {
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faArrowUpRightFromSquare,
  faBan,
  faBell,
  faBolt,
  faBoxOpen,
  faCalculator,
  faCalendarDay,
  faCamera,
  faCaretDown,
  faChartLine,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCircleUser,
  faClock,
  faCoins,
  faComments,
  faCopy,
  faCube,
  faCubes,
  faDownload,
  faEllipsisVertical,
  faEnvelope,
  faEuroSign,
  faEye,
  faEyeSlash,
  faFileArrowUp,
  faFilter,
  faFingerprint,
  faFlag,
  faCartShopping,
  faGavel,
  faGear,
  faGlobe,
  faHammer,
  faHandshake,
  faHouse,
  faImage,
  faKey,
  faLanguage,
  faLaptop,
  faLayerGroup,
  faLink,
  faLocationDot,
  faLock,
  faMagnifyingGlass,
  faMoon,
  faPaperPlane,
  faPen,
  faPhone,
  faPlus,
  faPrint,
  faRotate,
  faShareNodes,
  faShieldHalved,
  faSort,
  faSpinner,
  faStar,
  faSun,
  faTag,
  faTags,
  faTrash,
  faTriangleExclamation,
  faUser,
  faUserGear,
  faUserPlus,
  faUsers,
  faUserShield,
  faWandMagicSparkles,
  faWeightHanging,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
import {
  faFacebook,
  faLinkedin,
  faWhatsapp,
  faXTwitter,
} from '@fortawesome/free-brands-svg-icons';
import { colors } from '../theme/theme';

/**
 * Central icon registry. The app uses Font Awesome only — never emoji.
 */
export const ICONS = {
  whatsapp: faWhatsapp,
  xTwitter: faXTwitter,
  facebook: faFacebook,
  linkedin: faLinkedin,
  home: faHouse,
  search: faMagnifyingGlass,
  filter: faFilter,
  sort: faSort,
  plus: faPlus,
  close: faXmark,
  check: faCheck,
  checkCircle: faCircleCheck,
  info: faCircleInfo,
  warning: faTriangleExclamation,
  error: faCircleExclamation,
  back: faArrowLeft,
  arrowRight: faArrowRight,
  external: faArrowUpRightFromSquare,
  chevronDown: faCaretDown,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  more: faEllipsisVertical,
  trash: faTrash,
  edit: faPen,
  copy: faCopy,
  link: faLink,
  share: faShareNodes,
  refresh: faRotate,
  spinner: faSpinner,

  cube: faCube,
  cubes: faCubes,
  layers: faLayerGroup,
  print: faPrint,
  hammer: faHammer,
  cart: faCartShopping,
  handshake: faHandshake,
  calculator: faCalculator,
  bolt: faBolt,
  weight: faWeightHanging,
  coins: faCoins,
  euro: faEuroSign,
  gavel: faGavel,
  box: faBoxOpen,
  magic: faWandMagicSparkles,

  bell: faBell,
  user: faUser,
  userCircle: faCircleUser,
  users: faUsers,
  userPlus: faUserPlus,
  userGear: faUserGear,
  userShield: faUserShield,
  shield: faShieldHalved,
  key: faKey,
  fingerprint: faFingerprint,
  lock: faLock,
  ban: faBan,
  flag: faFlag,
  gear: faGear,
  sun: faSun,
  moon: faMoon,
  language: faLanguage,
  laptop: faLaptop,
  globe: faGlobe,

  tag: faTag,
  tags: faTags,
  eye: faEye,
  eyeOff: faEyeSlash,
  comments: faComments,
  clock: faClock,
  calendar: faCalendarDay,
  location: faLocationDot,
  envelope: faEnvelope,
  send: faPaperPlane,
  phone: faPhone,
  image: faImage,
  camera: faCamera,
  upload: faFileArrowUp,
  download: faDownload,
  chart: faChartLine,
  star: faStar,
  logout: faArrowRightFromBracket,
} as const;

export type IconName = keyof typeof ICONS;

export interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  style?: any;
}

export function Icon({ name, size = 16, color = colors.text, style }: IconProps) {
  return <FontAwesomeIcon icon={ICONS[name]} size={size} color={color} style={style} />;
}

export default Icon;
